title                : Trans Research Masterdoc
description          : Based on the Nominal.Naomi research masterdoc, this is an open source masterdoc on research on transgender individuals
locale               : en_US
keywords:
  - Trans
  - Research
  - NominalNaomi
tags:
  - Trans
  - Research
  - NominalNaomi

encoding             : "utf-8"