title                : "Blahaj Institute Trans Research Masterdoc"
tagline              : "An Open Source Research Master Document on Transgender and Neurodiverse issues."
description          : "The Blahaj Research Institute Trans Research Master Document is an open source master document created by SkyMochi64 for research on transgender and neurodivergent individuals based on the original Nominal.Naomi Research Masterdoc." 
locale               : "en_US"

url                  : https://www.masterdoc.info/
repository           : https://github.com/Blahaj-Research-Institute/ResearchMasterdoc

logo                 : https://www.masterdoc.info/assets/images/PFP_V1.png
image                : https://www.masterdoc.info/assets/images/PFP_V1.png


keywords:
  - Trans
  - Research
  - NominalNaomi
  - SkyMochi64
tags:
  - Trans
  - Research
  - NominalNaomi

encoding             : "utf-8"

author:
  name               : "Blahaj Research Institute"
  avatar             : "https://www.masterdoc.info/assets/images/PFP_V1.png"

plugins:
  - jekyll-seo-tag